# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sss.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from load_env import INACCESS_USERNAME, INACCESS_PASSWORD
from write_config import write_to_ini
from entry_point import start_automation


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 290, 101, 31))

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)

        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.save_keys)

        self.inaccess_username = QtWidgets.QLineEdit(self.centralwidget)
        self.inaccess_username.setGeometry(QtCore.QRect(390, 170, 151, 31))
        self.inaccess_username.setText("")
        self.inaccess_username.setObjectName("inaccess_username")

        self.inaccess_userlabel = QtWidgets.QLabel(self.centralwidget)
        self.inaccess_userlabel.setGeometry(QtCore.QRect(220, 160, 161, 41))
        self.inaccess_userlabel.setFont(font)
        self.inaccess_userlabel.setObjectName("inaccess_userlabel")

        self.inaccess_paslabel = QtWidgets.QLabel(self.centralwidget)
        self.inaccess_paslabel.setGeometry(QtCore.QRect(220, 200, 161, 41))
        self.inaccess_paslabel.setFont(font)
        self.inaccess_paslabel.setObjectName("inaccess_paslabel")

        self.inaccess_password = QtWidgets.QLineEdit(self.centralwidget)
        self.inaccess_password.setGeometry(QtCore.QRect(390, 210, 151, 31))
        self.inaccess_password.setText("")
        self.inaccess_password.setObjectName("inaccess_password")
        self.inaccess_password.setEchoMode(QtWidgets.QLineEdit.Password)

        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(220, 330, 321, 71))
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.start_button.clicked.connect(start_automation)

        self.edit_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_button.setGeometry(QtCore.QRect(390, 290, 101, 31))
        self.edit_button.setFont(font)
        self.edit_button.setObjectName("edit_button")
        self.edit_button.clicked.connect(self.edit_keys)

        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(290, 250, 161, 41))
        self.error_label.setFont(font)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        if INACCESS_USERNAME and INACCESS_PASSWORD:
            self.set_saved_values()

    def set_saved_values(self):
        self.inaccess_username.setText(INACCESS_USERNAME)
        self.inaccess_password.setText(INACCESS_PASSWORD)
        self.inaccess_username.setDisabled(True)
        self.inaccess_password.setDisabled(True)
        self.pushButton.setDisabled(True)

    def edit_keys(self):
        self.inaccess_username.setReadOnly(False)
        self.inaccess_password.setReadOnly(False)
        self.inaccess_username.setEnabled(True)
        self.inaccess_password.setEnabled(True)
        self.pushButton.setEnabled(True)

    def save_keys(self):
        username = self.inaccess_username.text()
        password = self.inaccess_password.text()
        if username == "" and password == "":
            self.error_label.setText("username and password field cannot be empty")
            self.error_label.adjustSize()

        elif username == "":
            self.error_label.setText("username  field cannot be empty")
            self.error_label.adjustSize()

        elif password == "":
            self.error_label.setText("username  field cannot be empty")

        else:
            write_to_ini(username=username, password=password)
            self.inaccess_password.setDisabled(True)
            self.inaccess_username.setDisabled(True)
            self.pushButton.setDisabled(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
        self.inaccess_userlabel.setText(_translate("MainWindow", "Inaccess Username"))
        self.inaccess_paslabel.setText(_translate("MainWindow", "Inaccess Password"))
        self.start_button.setText(_translate("MainWindow", "Start Automation"))
        self.edit_button.setText(_translate("MainWindow", "Edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
